### PR TITLE
Add ID to the cookie for easy access

### PR DESCRIPTION
**Pull request by vblinden**
Hello,

I added the ID of the authenticated user to the cookie for easy access. The ID can be used for unique identification of the user.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#22](https://github.com/yegor256/glogin/issues/22); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@vblinden I think you have to modify the encryption part too, not only decryption.

**Comment by vblinden** [comment]
@yegor256 Didn't I do that in the `to_s` method in `cookie.rb`?

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor release, tag is `0.7.0`

**Comment by 0crat** [comment]
Job `gh:yegor256/glogin#22` is not assigned, can't get performer

**Pull request merged**
